### ISSUE TITLE
Investigate Assertion error in Server Handshake

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#132]
`2016-03-24 03:09:57,236 [WorkerThread(client_handshake_stage, 0)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(client_handshake_stage, 0),5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
com.tc.util.TCAssertionError: Assertion failed
	at com.tc.util.Assert.failure(Assert.java:55)
	at com.tc.util.Assert.eval(Assert.java:64)
	at com.tc.util.Assert.assertTrue(Assert.java:85)
	at com.tc.objectserver.handshakemanager.ServerClientHandshakeManager.notifyClientConnect(ServerClientHandshakeManager.java:137)
	at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:63)
	at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:37)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)`

**Comment by myronkscott** [comment]
This is a pretty interesting corner case.  It looks like if a client is destroying an entity and failover happens in the middle of destroy, the client will try and resend a destroy message on an entity that may or may not be there.  Should we assume that this is the only way this can happen and just ignore or if we try and track this, how can we do so?
