### ISSUE TITLE
Closing entity on a different thread to the entity fetch causes an IllegalMonitorStateException

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#211]
```
java.lang.IllegalMonitorStateException
	at com.tc.object.locks.ClientLockImpl.release(ClientLockImpl.java:794)
	at com.tc.object.locks.ClientLockImpl.unlock(ClientLockImpl.java:166)
	at com.tc.object.locks.ClientLockManagerImpl.unlock(ClientLockManagerImpl.java:198)
	at com.terracotta.connection.entity.MaintenanceModeService.unlock(MaintenanceModeService.java:85)
	at com.terracotta.connection.entity.MaintenanceModeService.readUnlockEntity(MaintenanceModeService.java:46)
	at com.terracotta.connection.entity.TerracottaEntityRef$1.run(TerracottaEntityRef.java:81)
	at com.tc.object.ClientEntityManagerImpl.internalRelease(ClientEntityManagerImpl.java:422)
	at com.tc.object.ClientEntityManagerImpl.access$500(ClientEntityManagerImpl.java:72)
	at com.tc.object.ClientEntityManagerImpl$3.run(ClientEntityManagerImpl.java:374)
	at com.tc.object.EntityClientEndpointImpl.close(EntityClientEndpointImpl.java:211)
```

**Comment by jd0-sag** [comment]
While the idea still requires more planning, this is probably best solved along-side the various issues we have had with maintenance mode by changing the client-entity dynamic from a distributed read-write lock to something more similar to reference counting (although more complex than that since it needs to handle disconnect, etc, and how to suspend a blocking destroy message).

**Comment by jd0-sag** [comment]
Assigning to @myronkscott as this will likely be either solved or become moot as a result of his current items.
