### ISSUE TITLE
Process creating Barrier entity in parallel is hung

### ISSUE THREAD

**Issue by kedar031** [Terracotta-OSS/terracotta-core#212]
When the following code is executed in parallel , one of the process creates the Barrier entity and goes ahead to wait on barrier.await() forever since the other process never is stuck in creating Barrier entity.

````java
Connection clusterConnection = ConnectionFactory.connect(CLUSTER_URI, new Properties());
    Barrier barrier=null;
    String jvmId = ManagementFactory.getRuntimeMXBean().getName();

    try{
      LOG.info(jvmId+" trying to  create Barrier entity");
      EntityRef<Barrier, BarrierConfig> ref = clusterConnection.getEntityRef(Barrier.class, Barrier.VERSION, "barrier");
      ref.create(new BarrierConfig(2));
      LOG.info(jvmId+" successfully created Barrier entity");
    } catch (EntityAlreadyExistsException e){
        //do nothing
      LOG.info(jvmId+" hit Entity Exists exception");
    }catch (Exception e){
      LOG.info("Hit a different one "+e );
    }

    barrier = clusterConnection.getEntityRef(Barrier.class, Barrier.VERSION, "barrier").fetchEntity();

    final CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder = configureCacheManager(CLUSTER_URI);
    final PersistentCacheManager cacheManager = clusteredCacheManagerBuilder.build(true);
    final Cache<Long, String> cache = cacheManager.getCache("clustered-cache", Long.class, String.class);

    int id = -1;
    try {
      LOG.info("Going to await for other threads " + jvmId);
      id = barrier.await();
    } catch (Exception e) {
      e.printStackTrace();
    }
````

Stack trace of the hung process:

````
"pool-2-thread-1" prio=6 tid=0x0000000013f74800 nid=0x2278 waiting on condition [0x000000001593d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007adb806d0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:317)
	at com.tc.object.locks.LockStateNode$PendingLockHold.park(LockStateNode.java:222)
	at com.tc.object.locks.ClientLockImpl.acquireQueued(ClientLockImpl.java:924)
	at com.tc.object.locks.ClientLockImpl.acquireQueued(ClientLockImpl.java:898)
	at com.tc.object.locks.ClientLockImpl.lock(ClientLockImpl.java:104)
	at com.tc.object.locks.ClientLockManagerImpl.lock(ClientLockManagerImpl.java:123)
	at com.terracotta.connection.entity.MaintenanceModeService.lock(MaintenanceModeService.java:66)
	at com.terracotta.connection.entity.MaintenanceModeService.enterMaintenanceMode(MaintenanceModeService.java:51)
	at com.terracotta.connection.entity.TerracottaEntityRef.create(TerracottaEntityRef.java:126)
	at com.terracotta.qa.ehcache.test.MultipleClientsTest.testBarrier(MultipleClientsTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by jd0-sag** [comment]
To provide some background, this is currently worked as designed but we want to change the expected behavior in order to avoid this specific lock usage, on the create.  Some of the semantics are still to be nailed down but I suspect that the change may just be to the way that create acquires the write lock on the entity coordinates.

The hard part is is figuring out how to manage the maintenance mode lock, from the client side.  While we moved the details of maintenance mode into the related calls, a while ago, the treatment of the distributed lock state is still the same.  `tryDestroy()` got around this by defining its behavior in terms of the lock state but we probably want something different for `create()`.

**Comment by myronkscott** [comment]
When the initial implementation of maintenance mode was conceived, this type of racing create was not an intended usage pattern.  Part of the problem is that tc-api was later changed to hide much of what maintenance mode is doing.  

While this is a serious issue, can this be worked around while we evaluate a new implementation based in the messaging layer rather than the lock manager?

**Comment by jd0-sag** [comment]
We have decided that, as a short-term work-around to support some different locking semantics in `EntityRef.create()`, it should use a `tryLock()`, instead of a `lock()`, and assume that any failure to acquire the lock implies that the entity already exists.

This is because of the shift, over time, from the original _maintenance mode_ locking semantics into a less structured approach where `create()` might be called at any point, by potentially multiple clients, outside of specific _maintenance_ operations.  This change in direction has meant that the explicit RW-lock semantics are no longer desirable.

As a short-term work-around to emulate the desired semantics (where `create()` can _fail fast_, without acquiring the lock, if the entity already exists), we will assume that a failure to acquire the lock implies that the entity exists.

Cases where this can happen and how this work-around is justified:

* Read-lock held:  if the entity has been fetched by any clients (read-lock), it clearly exists
* Write-lock held for create:  another client is currently creating the entity, so it would exist by the time this client acquired the lock
* Write-lock held for destroy:  another client is currently destroying the entity, but this operation is racy, so we can assume that a reasonable interpretation is that this client acquired the lock, first
* Write-lock held to destroy non-existent entity:  in this case, assuming that the entity exists would be incorrect, since it wasn't there before or after the other client acquired the lock, but we expect that this will be a usage error in current EhCache so it isn't expected

In the future, we will replace the lock manager with a sort of reference counting scheme so that this work-around can be replaced with a more complete solution without corner cases.
