### ISSUE TITLE
NPE during server startup on solaris

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-core#222]
Here's the stack trace:
```
java.lang.NullPointerException
        at com.tc.runtime.TCMemoryManagerImpl$MemoryMonitor.<init>(TCMemoryManagerImpl.java:126)
        at com.tc.runtime.TCMemoryManagerImpl.startMonitorIfNecessary(TCMemoryManagerImpl.java:105)
        at com.tc.runtime.TCMemoryManagerImpl.registerForMemoryEvents(TCMemoryManagerImpl.java:77)
        at com.tc.objectserver.impl.DistributedObjectServer.start(DistributedObjectServer.java:536)
        at com.tc.server.TCServerImpl.startDSOServer(TCServerImpl.java:446)
        at com.tc.server.TCServerImpl.access$300(TCServerImpl.java:77)
        at com.tc.server.TCServerImpl$StartAction.execute(TCServerImpl.java:423)
        at com.tc.lang.StartupHelper.startUp(StartupHelper.java:52)
        at com.tc.server.TCServerImpl.startServer(TCServerImpl.java:440)
        at com.tc.server.TCServerImpl.start(TCServerImpl.java:236)
        at com.tc.server.TCServerMain.main(TCServerMain.java:60)
```

**Comment by myronkscott** [comment]
Fixed with PR #224
