### ISSUE TITLE
Server crashes when it receives a message for an unknown entity

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-core#223]
Following is the error thrown by the server after it receives a message for the `org.ehcache.clustered.lock.client.VoltronReadWriteLockClient` entity that was not installed on its classpath:

```
com.tc.util.TCAssertionError: Unexpected exception in entity - CRASHING
        at com.tc.util.Assert.failure(Assert.java:41)
        at com.tc.objectserver.handler.ProcessTransactionHandler.addMessage(ProcessTransactionHandler.java:172)
        at com.tc.objectserver.handler.ProcessTransactionHandler.access$200(ProcessTransactionHandler.java:59)
        at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:87)
        at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:70)
        at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:199)
Caused by: java.lang.IllegalArgumentException: Can't handle entity type org.ehcache.clustered.lock.client.VoltronReadWriteLockClient
        at com.tc.objectserver.entity.ServerEntityFactory.getService(ServerEntityFactory.java:72)
        at com.tc.objectserver.entity.EntityManagerImpl.getVersionCheckedService(EntityManagerImpl.java:156)
        at com.tc.objectserver.entity.EntityManagerImpl.createEntity(EntityManagerImpl.java:99)
        at com.tc.objectserver.handler.EntityExistenceHelpers.createEntityReturnWasCached(EntityExistenceHelpers.java:56)
        at com.tc.objectserver.handler.ProcessTransactionHandler.addMessage(ProcessTransactionHandler.java:150)
        ... 5 more
```

Obviously, the server doesn't know how to handle such entity; but it should not crash but respond to the client with an error that eventually could be processed and transformed into a meaningful exception.

**Comment by myronkscott** [comment]
the plan is to throw a modified version of EntityNotFoundException instead of IllegalStateException when the entity is not on the class path.  This will avoid crash and transfer the exception to the client.
