### ISSUE TITLE
Healh monitoring agent connection refused when running in a container

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-core#279]
Hello,
I got the following output, when running the server in a container, and after a client joined : 
```
[TC] 2016-08-12 15:57:49,129 INFO - Health monitoring agent started for 172.17.0.1:60172
[TC] 2016-08-12 15:57:49,145 INFO - IOException attempting to finish socket connection
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at com.tc.net.core.CoreNIOServices$CommThread.doConnect(CoreNIOServices.java:710)
        at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:639)
        at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)
[TC] 2016-08-12 15:57:49,162 INFO - error event on connection com.tc.net.core.TCConnectionImpl@2110222167: connected: false, closed: false connect=[no connect time] idle=28ms [0 read, 0 write]: Connection refused
```

I used the following .tc.custom.log4j.properties
```
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} %5p %c{1}:%L - %m%n

log4j.rootLogger=WARN, stdout

log4j.logger.com.tc=WARN
log4j.logger.com.terracotta=INFO
log4j.logger.com.terracottatech=INFO
log4j.logger.org.terracotta=INFO
log4j.logger.tc.operator=INFO

log4j.logger.org.eclipse.jetty=INFO
log4j.logger.org.glassfish.jersey=INFO
```

Now, what's being different, running in a container, is that I only redirect port 9510, so any other (unknown) ports that the tc server binds, will be closed from the outside.

If I can't choose a port for this agent, can I disable it ? what's a stakes if I do ?
Thank you !

**Comment by myronkscott** [comment]
This section from tc.properties explains it better than I can.

```###########################################################################################
# Section :  HealthChecker { server(l2)->client(l1), server(l2)->server(l2) (HA), client(l1)->server(l2) }
#  ping.enabled         - If true, healthchecker is enabled.
#  ping.idletime        - Connection idletime (in milliseconds), after which healthchecker
#                         starts its ping test.
#  ping.interval        - The interval (in milliseconds) between healthchecker sending ping
#                         messages to the peer node which doesn't reply to its previous msgs.
#  ping.probes          - Total number of ping messages to be sent to the peer node before
#                         concluding the peer is dead.
#  socketConnect        - If true, apart from above ping-probe cycle, healthcheker does extra
#                         check like socket connect (to detect long GC) to see if the peer has
#                         any traces of life left
#  socketConnectCount   - Max number of successful socket connect that healthcheker
#                         can trust. Beyond which, no socket connects will be
#                         attempted and peer node is tagged as dead.
#  socketConnectTimeout - Socket timeout (integer, in number of ping.interval) when
#                         connecting to the peer node. On timeout, healthchecker
#                         concludes peer node as dead irrespective of previous
#                         successful socket connects.
#  checkTime.enabled    - If true, checking time difference between hosts is enabled.
#  checkTime.interval   - The interval (in milliseconds) between healthchecker attempting
#                         to find any time difference between hosts.
#  checkTime.threshold  - The maximum allowed time difference (in milliseconds) between hosts.
#                         Healthchecker logs a warning message if the time difference exceeds this limit.
###########################################################################################
# L2 -> L1  :
# These settings will detect a network disconnect (like a cable pull) in 10 seconds and
#   will allow a 40 second GC in the L1
l2.healthcheck.l1.ping.enabled = true
l2.healthcheck.l1.ping.idletime = 5000
l2.healthcheck.l1.ping.interval = 1000
l2.healthcheck.l1.ping.probes = 3
l2.healthcheck.l1.socketConnect = true
l2.healthcheck.l1.socketConnectTimeout = 5
l2.healthcheck.l1.socketConnectCount = 10
l2.healthcheck.l1.checkTime.enabled = true
l2.healthcheck.l1.checkTime.interval = 300000
l2.healthcheck.l1.checkTime.threshold = 300000

# L2 -> L2  : Networked Active-Passive
# These settings will detect a network disconnect (like a cable pull) in 10 seconds but
#   will allow a 40 second GC in the L2
l2.healthcheck.l2.ping.enabled = true
l2.healthcheck.l2.ping.idletime = 5000
l2.healthcheck.l2.ping.interval = 1000
l2.healthcheck.l2.ping.probes = 3
l2.healthcheck.l2.socketConnect = true
l2.healthcheck.l2.socketConnectTimeout = 5
l2.healthcheck.l2.socketConnectCount = 10
l2.healthcheck.l2.checkTime.enabled = true
l2.healthcheck.l2.checkTime.interval = 300000
l2.healthcheck.l2.checkTime.threshold = 300000

# L1 -> L2  : Health check
# These settings will detect a network disconnect (like a cable pull) in 10 seconds but
#   will allow upto 50 seconds GC in the L2
# L1's CallbackPort Listener can be by assigned randomly by the operating system:
#   bindPort = 0
# L1's CallbackPort Listener can be disabled with the following property:
#   bindPort = -1
# L1's CallbackPort Listener can be configured with a list of port ranges. For example:
#   bindPort = 8000,8100-8110,9000-10000,45000
l1.healthcheck.l2.bindAddress = 0.0.0.0
l1.healthcheck.l2.bindPort = 0
l1.healthcheck.l2.ping.enabled = true
l1.healthcheck.l2.ping.idletime = 5000
l1.healthcheck.l2.ping.interval = 1000
l1.healthcheck.l2.ping.probes = 3
l1.healthcheck.l2.socketConnect = true
l1.healthcheck.l2.socketConnectTimeout = 5
l1.healthcheck.l2.socketConnectCount = 13
l1.healthcheck.l2.checkTime.enabled = true
l1.healthcheck.l2.checkTime.interval = 300000
l1.healthcheck.l2.checkTime.threshold = 300000
```

**Comment by anthonydahanne** [comment]
thank you @myronkscott  for the clarification !
