### ISSUE TITLE
Error in ManagedEntityImpl.releaseEntity()

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#305]
This error is observed sporadically in the server log during ehcache test runs when cache manager is destroyed. From the log, it sounds like ManagedEntityImpl.releaseEntity() tries to respond to client even after connection with client is closed. 

2016-09-11 20:37:28,032 [WorkerThread(channel_life_cycle_stage, 0)] INFO com.tc.objectserver.handler.ChannelLifeCycleHandler - : Received transport disconnect.  Shutting down client ClientID[4]
2016-09-11 20:37:28,032 [WorkerThread(request_processor_stage, 0, 4)] WARN com.tc.net.protocol.tcm.TCMessageImpl - message not sent
java.io.IOException: connection not established
	at com.tc.net.protocol.transport.MessageTransportBase.send(MessageTransportBase.java:185)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.send(AbstractMessageChannel.java:206)
	at com.tc.net.protocol.tcm.ServerMessageChannelImpl.send(ServerMessageChannelImpl.java:33)
	at com.tc.net.protocol.tcm.TCMessageImpl.basicSend(TCMessageImpl.java:395)
	at com.tc.net.protocol.tcm.TCMessageImpl.send(TCMessageImpl.java:385)
	at com.tc.objectserver.entity.AbstractServerEntityRequestResponse.lambda$complete$60(AbstractServerEntityRequestResponse.java:131)
	at com.tc.objectserver.entity.AbstractServerEntityRequestResponse$$Lambda$16/1061180039.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.tc.objectserver.entity.AbstractServerEntityRequestResponse.complete(AbstractServerEntityRequestResponse.java:122)
	at com.tc.objectserver.entity.ServerEntityRequestResponse.complete(ServerEntityRequestResponse.java:60)
	at com.tc.objectserver.handler.ProcessTransactionHandler$$Lambda$17/646081244.accept(Unknown Source)
	at com.tc.objectserver.entity.ManagedEntityImpl$ResultCapture.complete(ManagedEntityImpl.java:1053)
	at com.tc.objectserver.entity.ManagedEntityImpl.releaseEntity(ManagedEntityImpl.java:691)
	at com.tc.objectserver.entity.ManagedEntityImpl.invokeLifecycleOperation(ManagedEntityImpl.java:330)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processLifecycleEntity$49(ManagedEntityImpl.java:198)
	at com.tc.objectserver.entity.ManagedEntityImpl$$Lambda$13/1043059596.run(Unknown Source)
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:897)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:162)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:154)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
	at com.tc.async.impl.StageQueueImpl$FlushingHandledContext.runWithHandler(StageQueueImpl.java:527)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

**Comment by myronkscott** [comment]
this is expected behavior.  The server side does not know that the client already closed the channel until a queued message is attempted to be sent.  We will try and suppress some warnings if the channel has been purposely closed.
