### ISSUE TITLE
Passive server crashes during reconnection

### ISSUE THREAD

**Issue by henri-tremblay** [Terracotta-OSS/terracotta-core#320]
With

	2016-10-12 21:43:56,377 [WorkerThread(client_handshake_stage, 0)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(client_handshake_stage, 0),5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
	com.tc.exception.TCRuntimeException: Uncaught exception in stage
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:211)
	Caused by: java.nio.BufferUnderflowException
		at java.nio.Buffer.nextGetIndex(Buffer.java:506)
		at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
		at org.ehcache.clustered.common.internal.messages.ReconnectDataCodec.decode(ReconnectDataCodec.java:46)
		at org.ehcache.clustered.server.EhcacheActiveEntity.handleReconnect(EhcacheActiveEntity.java:284)
		at com.tc.objectserver.entity.ManagedEntityImpl.reconnectClient(ManagedEntityImpl.java:307)
		at com.tc.objectserver.handshakemanager.ServerClientHandshakeManager.notifyClientConnect(ServerClientHandshakeManager.java:146)
		at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:68)
		at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:38)
		at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

This occurred during `BasicClusteredCacheCRUDReplicationTest.testCAS` on the PR ehcache/ehcache3#1527 that should be totally unrelated.

`testCAS` starts an active and a passive. The active is stopped and in `putIfAbsent` is done. The client tries to reconnect to the server, the server crash and the client keeps reconnecting forever. So the test never finishes.

**Comment by myronkscott** [comment]
This looks like a problem with the codec in ehcache correct?  If so please close this and re-file in ehcache.  The server is designed to crash on any unhanded exception (what is occurring here).

**Comment by henri-tremblay** [comment]
This is quite surprising. This seems to have been caused by the client doing `createCache` and then `validateCache`. Which is the kind of thing that could happen.

I'm seeing something to meditate here.
