### ISSUE TITLE
NPE when inserting null parents (management)

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#334]
At some point, we are calling:

monitoringProducer.addNode(null, "registry", registry);

either from an active, or from a passive.

I have the following stacktrace:

```
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1] 2016-10-24 15:49:10,424 [WorkerThread(request_processor_stage, 1, 17)] ERROR org.ehcache.clustered.server.EhcachePassiveEntity - Unexpected exception raised during operation: LIFECYCLE_OP#CONFIGURE
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1] java.lang.NullPointerException
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.services.LocalMonitoringProducer.findParent(LocalMonitoringProducer.java:252)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.services.LocalMonitoringProducer.addNodeFromShim(LocalMonitoringProducer.java:199)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.services.LocalMonitoringProducer.access$000(LocalMonitoringProducer.java:42)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.services.LocalMonitoringProducer$1.addNode(LocalMonitoringProducer.java:76)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.terracotta.management.service.monitoring.DefaultMonitoringService.exposeServerEntityManagementRegistry(DefaultMonitoringService.java:307)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.terracotta.management.service.registry.DefaultConsumerManagementRegistry.refresh(DefaultConsumerManagementRegistry.java:72)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.ehcache.clustered.server.EhcachePassiveEntity.configure(EhcachePassiveEntity.java:214)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.ehcache.clustered.server.EhcachePassiveEntity.invokeLifeCycleOperation(EhcachePassiveEntity.java:193)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:81)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:61)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:633)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:378)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$64(ManagedEntityImpl.java:236)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:898)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:152)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:144)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1]     at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1] 2016-10-24 15:49:12,419 [CommonShutDownHook] INFO com.terracottatech.tsa - L2 Exiting...
   [org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest][testServer1] server process died with rc=2
   [Interlock] serverDidShutdown: Server "testServer1": 16785ec0-21ff-478f-b8d6-7c4190b7af0b
``

parents can be null, api does not enforce non null, and it was working before.

**Comment by myronkscott** [comment]
I can make the NPE go away but it will still mean that the value will not be stored.  Is that acceptable?

**Comment by mathieucarbou** [comment]
Ok. Event if we pass `new String[0]` ? What are you talking about when you say "stored" ?

**Comment by myronkscott** [comment]
Disregard my last comment
