### ISSUE TITLE
Client never stops when connected to server

### ISSUE THREAD

**Issue by henri-tremblay** [Terracotta-OSS/terracotta-core#377]
Launching the following main

```java
  public static void main(String[] args) {
    URI clusterURI = URI.create("terracotta://tc-bigmemory-11.eur.ad.sag:9510/cachemanager");

    CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder =
      CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
          .autoCreate().defaultServerResource("primary-server-resource"))
        .withCache("clustered-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, byte[].class,
          ResourcePoolsBuilder.newResourcePoolsBuilder()
            .with(ClusteredResourcePoolBuilder.clusteredDedicated(128, MemoryUnit.GB))));

    clusteredCacheManagerBuilder.build(true); // this throws the TimeoutException
  }
```

It will never exit. The main thread is dead. Here is the stack dump. Some of these threads need to be daemon.

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode):

"DestroyJavaVM" #26 prio=5 os_prio=31 tid=0x00007fda39a7e800 nid=0x1c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Out of band notifier - Main" #25 daemon prio=5 os_prio=31 tid=0x00007fda3a143000 nid=0x7107 waiting on condition [0x000070000f057000]
   java.lang.Thread.State: WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076ec22668> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at com.tc.cluster.ClusterImpl$OutOfBandNotifier$1.run(ClusterImpl.java:417)
  at java.lang.Thread.run(Thread.java:745)

"WorkerThread(multi_request_ack_stage, 0)" #23 daemon prio=5 os_prio=31 tid=0x00007fda3b020800 nid=0x6f03 waiting on condition [0x000070000ef54000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb00750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_membership_event_stage, 0)" #22 daemon prio=5 os_prio=31 tid=0x00007fda3b86c800 nid=0x6d03 waiting on condition [0x000070000ee51000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb18198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(server_entity_message_stage, 0)" #21 daemon prio=5 os_prio=31 tid=0x00007fda3b86a800 nid=0x6b03 waiting on condition [0x000070000ed4e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb088d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(request_ack_stage, 0)" #20 daemon prio=5 os_prio=31 tid=0x00007fda3789c000 nid=0x6903 waiting on condition [0x000070000ec4b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb20198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(hydrate_message_stage, 0)" #19 daemon prio=5 os_prio=31 tid=0x00007fda3789b000 nid=0x6703 waiting on condition [0x000070000eb48000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb28198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(client_coordination_stage, 0)" #18 daemon prio=5 os_prio=31 tid=0x00007fda37932000 nid=0x6503 waiting on condition [0x000070000ea45000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb30198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_events_stage, 0)" #17 daemon prio=5 os_prio=31 tid=0x00007fda37931800 nid=0x6303 waiting on condition [0x000070000e942000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x000000076eb38198> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
  at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
  at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"TC Memory Monitor" #16 prio=5 os_prio=31 tid=0x00007fda378bf000 nid=0x6103 waiting on condition [0x000070000e83f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
  at java.lang.Thread.sleep(Native Method)
  at com.tc.runtime.TCMemoryManagerImpl$MemoryMonitor.run(TCMemoryManagerImpl.java:140)

"HealthChecker" #15 daemon prio=5 os_prio=31 tid=0x00007fda37930000 nid=0x5f03 in Object.wait() [0x000070000e73c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
  at java.lang.Object.wait(Native Method)
  - waiting on <0x000000076eb183b0> (a com.tc.util.concurrent.SetOnceFlag)
  at com.tc.net.protocol.transport.ConnectionHealthCheckerImpl$HealthCheckerMonitorThreadEngine.run(ConnectionHealthCheckerImpl.java:247)
  - locked <0x000000076eb183b0> (a com.tc.util.concurrent.SetOnceFlag)
  at java.lang.Thread.run(Thread.java:745)

"L1_L2:TCComm Main Selector Thread_W (listen 0:0:0:0:0:0:0:0:61558)" #14 daemon prio=5 os_prio=31 tid=0x00007fda3792d000 nid=0x5d03 runnable [0x000070000e639000]
   java.lang.Thread.State: RUNNABLE
  at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  - locked <0x000000076eb30448> (a sun.nio.ch.Util$3)
  - locked <0x000000076eb30458> (a java.util.Collections$UnmodifiableSet)
  - locked <0x000000076eb303f8> (a sun.nio.ch.KQueueSelectorImpl)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
  at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
  at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"L1_L2:TCComm Main Selector Thread_R (listen 0:0:0:0:0:0:0:0:61558)" #13 daemon prio=5 os_prio=31 tid=0x00007fda378e9000 nid=0x5b03 runnable [0x000070000e536000]
   java.lang.Thread.State: RUNNABLE
  at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  - locked <0x000000076eb20448> (a sun.nio.ch.Util$3)
  - locked <0x000000076eb20458> (a java.util.Collections$UnmodifiableSet)
  - locked <0x000000076eb203f8> (a sun.nio.ch.KQueueSelectorImpl)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
  at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
  at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"SampledCounterManager Timer" #12 daemon prio=5 os_prio=31 tid=0x00007fda378d8000 nid=0x5903 in Object.wait() [0x000070000e433000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
  at java.lang.Object.wait(Native Method)
  - waiting on <0x000000076eb08b08> (a java.util.TaskQueue)
  at java.util.TimerThread.mainLoop(Timer.java:552)
  - locked <0x000000076eb08b08> (a java.util.TaskQueue)
  at java.util.TimerThread.run(Timer.java:505)
```

**Comment by myronkscott** [comment]
The issue here is that the inflight queue may still have some pending items so we cannot make everything daemon.  TC memory monitor thread probably should go away.  I don't think that is of much use anymore.  The rest is related to networking.  Is there a way to use a try-finally block in ehcache and make sure the underlying connection is closed?

**Comment by henri-tremblay** [comment]
Can you explain why you care about inflight? For me, it's not different from a server crash. There will be inflights. That are processed or not.

Then, we could decide that a `CacheManager` needs to be closed like a stream. But having it preventing to shutdown the server still feels harsh. @ljacomet Thoughts?
