### ISSUE TITLE
ArrayIndexOutOfBoundsException in StageQueueImpl.findShortestQueueIndex

### ISSUE THREAD

**Issue by kcleereman** [Terracotta-OSS/terracotta-core#484]
During a long-running test I encountered the following exception on the server (this was when using four clients on a single enterprise server):

com.tc.exception.TCRuntimeException: Uncaught exception in stage
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:211)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -58
        at com.tc.async.impl.StageQueueImpl.findShortestQueueIndex(StageQueueImpl.java:197)
        at com.tc.async.impl.StageQueueImpl.getSourceQueueFor(StageQueueImpl.java:213)
        at com.tc.async.impl.StageQueueImpl.addMultiThreaded(StageQueueImpl.java:141)
        at com.tc.objectserver.entity.RequestProcessor.scheduleRequest(RequestProcessor.java:86)
        at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.start(ManagedEntityImpl.java:1019)
        at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.access$000(ManagedEntityImpl.java:976)
        at com.tc.objectserver.entity.ManagedEntityImpl.scheduleInOrder(ManagedEntityImpl.java:279)
        at com.tc.objectserver.entity.ManagedEntityImpl.processInvokeRequest(ManagedEntityImpl.java:308)
        at com.tc.objectserver.entity.ManagedEntityImpl.addRequestMessage(ManagedEntityImpl.java:192)
        at com.tc.objectserver.handler.ProcessTransactionHandler.addMessage(ProcessTransactionHandler.java:294)
        at com.tc.objectserver.handler.ProcessTransactionHandler.access$400(ProcessTransactionHandler.java:75)
        at com.tc.objectserver.handler.ProcessTransactionHandler$2.handleEvent(ProcessTransactionHandler.java:140)
        at com.tc.objectserver.handler.ProcessTransactionHandler$2.handleEvent(ProcessTransactionHandler.java:122)
        at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

[terracotta-server.txt](https://github.com/Terracotta-OSS/terracotta-core/files/765312/terracotta-server.txt)

**Comment by kcleereman** [comment]
I re-ran the test and got an identical exception - arrayindexoutofbounds at -58
