### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#491]
Running into this error on server side with latest kit.

2017-02-15 23:10:15,586 [WorkerThread(client_handshake_stage, 0)] INFO com.tc.objectserver.handshakemanager.ServerClientHandshakeManager - Handling client handshake for ClientID[0]
2017-02-15 23:10:15,587 [WorkerThread(client_handshake_stage, 0)] INFO com.tc.objectserver.handshakemanager.ServerClientHandshakeManager - Sending handshake acknowledgement to ClientID[0]
2017-02-15 23:10:15,615 [WorkerThread(hydrate_message_stage, 0, 4)] ERROR com.tc.net.protocol.tcm.HydrateHandler - Error hydrating message of type VOLTRON_ENTITY_MESSAGE (17)
java.lang.ArrayIndexOutOfBoundsException: 1668052339
	at com.tc.entity.NetworkVoltronEntityMessageImpl.hydrateValue(NetworkVoltronEntityMessageImpl.java:184)
	at com.tc.net.protocol.tcm.TCMessageImpl.hydrate(TCMessageImpl.java:178)
	at com.tc.net.protocol.tcm.HydrateHandler.handleEvent(HydrateHandler.java:34)
	at com.tc.net.protocol.tcm.HydrateHandler.handleEvent(HydrateHandler.java:26)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

**Comment by myronkscott** [comment]
Can you double check that there is no client server version mis-match.  There were some protocol changes in the latest.

**Comment by esebasti** [comment]
Thx. Client was pointing to old version.
