### ISSUE TITLE
EntityRef.create never returns even if a timeout was set

### ISSUE THREAD

**Issue by henri-tremblay** [Terracotta-OSS/terracotta-core#495]
I'm starting a server which crashes because of a service that can't be found. The test client never gets a client even if there should be one.

The code is something along the line of:
```java
Cluster CLUSTER = new BasicExternalCluster(new File("build/cluster"), 1, Collections.emptyList(), "", RESOURCE_CONFIG, "");
CLUSTER.getClusterControl().waitForActive();
URI uri = CLUSTER.getConnectionURI();
Properties properties = new Properties();
properties.put(ConnectionPropertyNames.CONNECTION_TIMEOUT, "10000");
Connection managementConnection = ConnectionFactory.connect(uri, properties);
NmsEntityFactory entityFactory = new NmsEntityFactory(managementConnection, AbstractClusteringManagementTest.class.getName());
NmsEntity tmsAgentEntity = entityFactory.retrieveOrCreate(new NmsConfig()); // stuck here
```

This is the thread dump:
```
 java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.tc.object.InFlightMessage.waitForAcks(InFlightMessage.java:95)
	  at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:141)
	  at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:122)
	  at com.tc.object.ClientEntityManagerImpl$2.addSingleThreaded(ClientEntityManagerImpl.java:163)
	  at com.tc.object.ClientEntityManagerImpl.createInFlightMessageAfterAcks(ClientEntityManagerImpl.java:538)
	  at com.tc.object.ClientEntityManagerImpl.sendMessageWhileBusy(ClientEntityManagerImpl.java:506)
	  at com.tc.object.ClientEntityManagerImpl.createEntity(ClientEntityManagerImpl.java:251)
	  at com.terracotta.connection.entity.TerracottaEntityRef.create(TerracottaEntityRef.java:117)
	  at org.terracotta.management.entity.nms.client.NmsEntityFactory.create(NmsEntityFactory.java:68)
	  at org.terracotta.management.entity.nms.client.NmsEntityFactory.retrieveOrCreate(NmsEntityFactory.java:46)
```

As a side note, having a method `Cluster.newConnection(Properties)` seems to be a useful addition to prevent to go through the `ConnectionFactory`.

**Comment by myronkscott** [comment]
The timeout in the properties object is for connect only.  Once the initial connection has been established, we require to connection to be closed to break out of this wait.  This may not be ideal as there have been several discussions on how to handle the situation when there is no server with no real consensus yet on what the correct behavior should be.  I will leave this open for now as another discussion point around the topic but I would not expect an immediate solution other than Connection.close()

**Comment by myronkscott** [comment]
As designed
