### ISSUE TITLE
Active crashes when trying to zap passive from cluster

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#526]
This is observed sporadically from ehcache tests when passive is trying to join cluster with dirty db or after network partition. Here is the exception.

2017-03-30 21:35:44,649 WARN - Requesting node to quit : NodeID : NodeID[localhost:9610] Error Type : Two or more Active servers detected in the cluster
2017-03-30 21:35:44,652 WARN - Requesting node to quit : NodeID : NodeID[localhost:9610] Error Type : COMMUNICATION ERROR
com.tc.exception.TCRuntimeException: Uncaught exception in stage
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:206)
Caused by: java.lang.NullPointerException: object is null
at com.tc.util.Assert.assertNotNull(Assert.java:144)
at com.tc.util.Assert.assertNotNull(Assert.java:153)
at com.tc.services.LocalMonitoringProducer.handleRemoteAdd(LocalMonitoringProducer.java:198)
at com.tc.l2.handler.PlatformInfoRequestHandler$1.handleEvent(PlatformInfoRequestHandler.java:73)
at com.tc.l2.handler.PlatformInfoRequestHandler$1.handleEvent(PlatformInfoRequestHandler.java:58)
at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:192)

**Comment by jd0-sag** [comment]
How often does this happen and can you describe other aspects of the deployment (how many servers, how many clients, how far into a run, etc)?

**Comment by myronkscott** [comment]
PR #535
