### ISSUE TITLE
NPE when terminating a server by using the diagnostic port

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#550]
```
017-05-05 16:42:14.135 ERROR 44226 --- [ XNIO-2 task-61] customer.logger.tsa                      : Error stopping stage manager

java.lang.NullPointerException: null
	at com.tc.async.impl.StageImpl.stopThreads(StageImpl.java:134) ~[terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.async.impl.StageImpl.destroy(StageImpl.java:88) ~[terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.async.impl.StageManagerImpl.stopAll(StageManagerImpl.java:147) ~[terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.DistributedObjectClient.shutdownResources(DistributedObjectClient.java:572) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.ClientShutdownManager.shutdown(ClientShutdownManager.java:118) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.ClientShutdownManager.execute(ClientShutdownManager.java:77) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.DistributedObjectClient.shutdownClient(DistributedObjectClient.java:714) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:734) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:555) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.terracotta.diagnostic.DiagnosticClientImpl.shutdown(DiagnosticClientImpl.java:81) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.terracotta.connection.api.DiagnosticConnectionService$1.run(DiagnosticConnectionService.java:86) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.terracotta.connection.TerracottaConnection.close(TerracottaConnection.java:79) [terracotta-common-client-10.1.0-SNAPSHOT.jar!/:na]
	at com.terracottatech.management.server.cluster.HealthService.doWithDiagnostics(HealthService.java:324) [classes!/:10.1.0-SNAPSHOT]
	at com.terracottatech.management.server.cluster.HealthService.doWithDiagnostics(HealthService.java:280) [classes!/:10.1.0-SNAPSHOT]
	at com.terracottatech.management.server.cluster.HealthService.forceTerminateServer(HealthService.java:201) [classes!/:10.1.0-SNAPSHOT]
	at com.terracottatech.management.server.cluster.HealthService$$FastClassBySpringCGLIB$$4a44b1f.invoke(<generated>) [classes!/:10.1.0-SNAPSHOT]
```

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI

**Comment by mathieucarbou** [comment]
@myronkscott : I get a similar bug when trying to get the server status. Is it the same issue ?

```
017-05-09 11:19:13.122  INFO 56626 --- [     TMS-Task-1] customer.logger.tsa                      : shuting down Terracotta Client hook=false force=false
2017-05-09 11:19:13.122  INFO 56626 --- [ce36cdab762e788] console.logger                           : Connection successfully established to server at null
2017-05-09 11:19:13.123  INFO 56626 --- [ce36cdab762e788] customer.logger.tsa                      : Connection successfully established to server at null
2017-05-09 11:19:13.124 ERROR 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Error stopping stage manager

java.lang.NullPointerException: null
	at com.tc.async.impl.StageImpl.stopThreads(StageImpl.java:134) ~[classes/:na]
	at com.tc.async.impl.StageImpl.destroy(StageImpl.java:88) ~[classes/:na]
	at com.tc.async.impl.StageManagerImpl.stopAll(StageManagerImpl.java:147) ~[classes/:na]
	at com.tc.object.DistributedObjectClient.shutdownResources(DistributedObjectClient.java:572) [classes/:na]
	at com.tc.object.ClientShutdownManager.shutdown(ClientShutdownManager.java:118) [classes/:na]
	at com.tc.object.ClientShutdownManager.execute(ClientShutdownManager.java:77) [classes/:na]
	at com.tc.object.DistributedObjectClient.shutdownClient(DistributedObjectClient.java:714) [classes/:na]
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:734) [classes/:na]
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:555) [classes/:na]
	at com.tc.object.DistributedObjectClientFactory.create(DistributedObjectClientFactory.java:112) [classes/:na]
	at com.terracotta.diagnostic.DiagnosticClientImpl.init(DiagnosticClientImpl.java:65) [classes/:na]
	at com.terracotta.connection.api.DiagnosticConnectionService.connect(DiagnosticConnectionService.java:75) [classes/:na]
	at com.terracottatech.management.server.cluster.HealthService.doWithDiagnostics(HealthService.java:327) [classes/:na]
	at com.terracottatech.management.server.cluster.HealthService.doWithDiagnosticsAsync(HealthService.java:300) [classes/:na]
	at com.terracottatech.management.server.cluster.HealthService.retrieveStateAsync(HealthService.java:85) [classes/:na]
	at com.terracottatech.management.server.cluster.HealthService$$FastClassBySpringCGLIB$$4a44b1f.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) [spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) [spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:321) [spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

2017-05-09 11:19:13.125  WARN 56626 --- [     TMS-Task-1] c.c.t.n.p.tcm.ClientMessageChannel       : Switcing channel state from INIT to CLOSED.
2017-05-09 11:19:13.125  INFO 56626 --- [     TMS-Task-1] .ConnectionHealthCheckerImpl: DSO Client : HealthChecker STOP requested
2017-05-09 11:19:13.125  INFO 56626 --- [  HealthChecker] .ConnectionHealthCheckerImpl: DSO Client : HealthChecker SHUTDOWN
2017-05-09 11:19:14.129  INFO 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Destroyed thread WorkerThread(client_coordination_stage, 0) time to destroy:1000 millis
2017-05-09 11:19:14.130  INFO 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Destroyed thread WorkerThread(hydrate_message_stage, 0) time to destroy:0 millis
2017-05-09 11:19:14.130  INFO 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Destroyed thread WorkerThread(request_ack_stage, 0) time to destroy:0 millis
2017-05-09 11:19:14.130  INFO 56626 --- [     TMS-Task-1] customer.logger.tsa                      : time to destroy thread group:1 seconds
2017-05-09 11:19:14.130  WARN 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Timed out waiting for TC thread group threads to die - probable shutdown memory leak
Live threads: [Thread[WorkerThread(client_coordination_stage, 0),5,TC Thread Group], Thread[WorkerThread(hydrate_message_stage, 0),5,TC Thread Group], Thread[WorkerThread(request_ack_stage, 0),5,TC Thread Group]]
2017-05-09 11:19:14.131  WARN 56626 --- [     TMS-Task-1] customer.logger.tsa                      : Spawning TCThreadGroup last chance cleaner thread
```
