### ISSUE TITLE
Standard error should not be dumped on the console

### ISSUE THREAD

**Issue by saurabhagas** [Terracotta-OSS/terracotta-core#563]
The following stacktrace is dumped on console from standard error (goes away from standard error is "turned off"). This interferes with command line utilities, and hampers their output. Please redirect it to an appropriate log file.

com.tc.exception.TCRuntimeException: java.lang.InterruptedException
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:196)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:347)

**Comment by myronkscott** [comment]
There is nothing in the code writing directly to stdout or stderr.  Is this possibly the uncaught exception handler printing to stderr?  What is the tool doing to interrupt WorkerThreads?

**Comment by ljacomet** [comment]
@myronkscott It is indeed the uncaught exception handler. This stack trace is sometimes printed when the connection times out.

**Comment by ramsai1729** [comment]
is this still happening? if so could you provide latest logs and way to reproduce the issue.

**Comment by saurabhagas** [comment]
The stacktrace isn't seen now. Thanks!

**Comment by ramsai1729** [comment]
Thanks for checking, please re-open or create a new issue if it happens again
