### ISSUE TITLE
NPE while recovering from a whole stripe failure

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-core#589]
if you try to recover from a full stripe failure, tc server won't start anymore (any server on the stripe)
You'll get on the console : 
```
2017-05-25 15:39:56,103 INFO - Terracotta Server instance has started up as ACTIVE node on 0:0:0:0:0:0:0:0:19510 successfully, and is now ready for work.
com.tc.exception.TCRuntimeException: Uncaught exception in stage
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:213)
Caused by: java.lang.NullPointerException
	at com.tc.objectserver.persistence.TransactionOrderPersistor.buildGlobalListIfNessessary(TransactionOrderPersistor.java:143)
	at com.tc.objectserver.persistence.TransactionOrderPersistor.getIndexToReplay(TransactionOrderPersistor.java:166)
	at com.tc.objectserver.handler.ProcessTransactionHandler.handleResentMessage(ProcessTransactionHandler.java:468)
	at com.tc.objectserver.handshakemanager.ServerClientHandshakeManager.notifyClientConnect(ServerClientHandshakeManager.java:140)
	at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:73)
	at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:39)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:199)
```

**Comment by myronkscott** [comment]
#597
