### ISSUE TITLE
AssertTrue fails in ManagementTopologyEventCollector.clientDidReleaseEntity

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-core#699]
when a client seems to disconnect from the the server, the server can crash while releasing its entity : 

```
2017-08-31 15:26:41.624  INFO   --- [or_stage, 2, 2)] c.t.o.impl.DistributedObjectServer      : completed lifecycle RELEASE_ENTITY on EntityID{className='com.terracottatech.store.client.DatasetEntity', entityName='datasetFromTCStoreSample'}
2017-08-31 15:26:41.625  INFO   --- [or_stage, 2, 2)] c.t.o.entity.ManagedEntityImpl          : Client:ClientID[134] Invoking lifecycle RELEASE_ENTITY on EntityID{className='com.terracottatech.store.client.DatasetEntity', entityName='datasetFromTCStoreSample'}
2017-08-31 15:26:41.626  INFO   --- [or_stage, 2, 2)] c.t.store.server.DatasetActiveEntity    : Client ClientDescriptorImpl{nodeID=ClientID[134], entityDescriptor=ClientInstanceID(5)} disconnected from dataset 'datasetFromTCStoreSample'
2017-08-31 15:26:41.627  INFO   --- [or_stage, 2, 2)] c.t.o.impl.DistributedObjectServer      : completed lifecycle RELEASE_ENTITY on EntityID{className='com.terracottatech.store.client.DatasetEntity', entityName='datasetFromTCStoreSample'}
com.tc.util.TCAssertionError: Assertion failed
at com.tc.util.Assert.failure(Assert.java:55)
at com.tc.util.Assert.eval(Assert.java:64)
at com.tc.util.Assert.assertTrue(Assert.java:85)
at com.tc.objectserver.core.impl.ManagementTopologyEventCollector.clientDidReleaseEntity(ManagementTopologyEventCollector.java:233)
```

**Comment by anthonydahanne** [comment]
@mathieucarbou FYI
