### ISSUE TITLE
Fix client disconnect completion

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#712]
```
                at com.tc.objectserver.entity.ManagedEntityImpl.invokeLifecycleOperation(ManagedEntityImpl.java:485) [dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processLifecycleEntity$0(ManagedEntityImpl.java:276) [dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:1135) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:171) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:162) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23) ~[dso-l2-5.3.3.jar:na]
                at com.tc.async.impl.MultiStageQueueImpl$FlushingHandledContext.runWithHandler(MultiStageQueueImpl.java:489) ~[common-5.3.3.jar:na]
                at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:224) ~[common-5.3.3.jar:na]
Caused by: java.lang.IllegalArgumentException: Unexpected action in complete() DISCONNECT_CLIENT
                at com.tc.objectserver.entity.AbstractServerEntityRequestResponse.lambda$complete$2(AbstractServerEntityRequestResponse.java:148) ~[dso-l2-5.3.3.jar:na]
                at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
                at com.tc.objectserver.entity.AbstractServerEntityRequestResponse.complete(AbstractServerEntityRequestResponse.java:134) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.ServerEntityRequestResponse.complete(ServerEntityRequestResponse.java:63) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.ManagedEntityImpl$ResultCapture.complete(ManagedEntityImpl.java:1338) ~[dso-l2-5.3.3.jar:na]
                at com.tc.objectserver.entity.ManagedEntityImpl.invokeLifecycleOperation(ManagedEntityImpl.java:469) [dso-l2-5.3.3.jar:na]
                ... 8 common frames omitted
```

**Comment by myronkscott** [comment]
PR #711
