### ISSUE TITLE
LocalConnectionClosedException has an incorrect message.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#759]
The content of the exception message for LocalConnectionClosedException is decided wholly by the super constructor, which never calls the `getEntityName()` and `getClassName()` methods, it just uses the hardcoded nulls in the super-constructor.  We'll need to change more here to get the exception message to show anything other than "null:null".

**Comment by myronkscott** [comment]
#760

**Comment by lorban** [comment]
With the changes, the entity now correctly appears in the `LocalConnectionClosedException`'s message. Unfortunately, there's still a confusing `null:null` left around in `ConnectionClosedException`'s message:

```
com.tc.object.LocalConnectionClosedException: com.terracottatech.store.client.DatasetEntity:LeaseTest - Connection closed under in-flight message
	at com.tc.object.ExceptionUtils.throwRuntimeExceptionWithLocalStack(ExceptionUtils.java:65)
	at com.tc.object.ExceptionUtils.addLocalStackTraceToEntityException(ExceptionUtils.java:34)
	at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:188)
	at com.tc.object.InFlightMessage.get(InFlightMessage.java:150)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:211)
...
Caused by: org.terracotta.exception.ConnectionClosedException: Entity: null:null Connection closed under in-flight message
	at com.tc.object.ClientEntityManagerImpl.throwClosedExceptionOnMessage(ClientEntityManagerImpl.java:470)
	at com.tc.object.ClientEntityManagerImpl.shutdown(ClientEntityManagerImpl.java:451)
	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdownCallbacks(ClientHandshakeManagerImpl.java:194)
	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdown(ClientHandshakeManagerImpl.java:91)
	at com.tc.object.ClientShutdownManager.closeLocalWork(ClientShutdownManager.java:94)
	at com.tc.object.ClientShutdownManager.execute(ClientShutdownManager.java:75)
	at com.tc.object.DistributedObjectClient.shutdownClient(DistributedObjectClient.java:702)
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:724)
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:543)
	at com.terracotta.connection.ClientHandleImpl.shutdown(ClientHandleImpl.java:35)
	at com.terracotta.connection.TerracottaInternalClientImpl.shutdown(TerracottaInternalClientImpl.java:95)
	at com.terracotta.connection.api.TerracottaConnectionService$1.run(TerracottaConnectionService.java:81)
	at com.terracotta.connection.TerracottaConnection.close(TerracottaConnection.java:86)
	at org.terracotta.lease.LeaseExpiryConnectionKillingThread.run(LeaseExpiryConnectionKillingThread.java:52)
```

Removing the `Entity null:null` but should lift all remaining confusion, so that the message would look like this: `org.terracotta.exception.ConnectionClosedException: Entity: null:null Connection closed under in-flight message`.

**Comment by myronkscott** [comment]
this is being closed in favor of https://github.com/Terracotta-OSS/terracotta-apis/issues/287
