### ISSUE TITLE
Do not replay passive's monitoring tree after the server did become active

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#781]
There is an inconsistency which is failing when we activate the assertions. The newly active server is receiving some `addNode()` calls with data related to the old passive server _after_ it became active.

Here are the logs:

1. `IStripeMonitoring.serverDidBecomeActive` is called on consumerId 0 (platform)
2. the active server is rebuilding the tree (`addNode()` calls on consumer id 0) like `[0] addNode(testServer1, platform, clients)`
3. at the end, we receive some calls on the channel used to send the addNode() and data calls from passive to active:

```
IStripeMonitoringDataListenerAdapter - [2] addNode(testServer1, , registry)
DefaultDataListener - [2] setState(2, testServer1, [registry])
```

These entries are not required to be kept and replayed because the monitoring tree is rebuilding already and we don't need the old data. Also, I cannot ignore these replays in the test (assert == true) because we could miss some m&m bugs (in example a statistic collector that is still running in background on the passive entity's consumerId).

So I suggest we just drop the tree after a failover. In a more general way, I think platform does not need to keep a copy of the monitoring tree. If some persistence are needed at one point and a replay is needed, perhaps it is up to the implementor to decide that ?

In our case, this replay is not needed and we have to deal with it, and is really hard to just  ignore.

```
2017-11-22 15:01:29,945 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] serverDidBecomeActive(testServer1)
2017-11-22 15:01:29,945 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverDidBecomeActive(testServer1)
2017-11-22 15:01:29,948 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.DefaultClientMonitoringService - [1] onBecomeActive()
2017-11-22 15:01:29,948 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.DefaultManagementService - [2] onBecomeActive()
2017-11-22 15:01:29,950 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE552315D0050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='SERVER_JOINED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1}, attributes={}}]}, {})
2017-11-22 15:01:29,953 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverStateChanged(testServer1, ACTIVE)
2017-11-22 15:01:29,953 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231610050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='SERVER_STATE_CHANGED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1}, attributes={activateTime=1511380882617, state=ACTIVE}}]}, {})
2017-11-22 15:01:29,954 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform, clients)
2017-11-22 15:01:29,954 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform, entities)
2017-11-22 15:01:29,954 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform/entities, org.terracotta.management.entity.sample.client.CacheEntitypet-clinic/pets3)
2017-11-22 15:01:29,954 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverEntityCreated(testServer1, PlatformEntity{isActive=true, typeName='org.terracotta.management.entity.sample.client.CacheEntity', consumerID=3, name='pet-clinic/pets'})
2017-11-22 15:01:29,955 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231630050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='SERVER_ENTITY_CREATED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/pets:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/pets, entityType=org.terracotta.management.entity.sample.client.CacheEntity, consumerId=3}, attributes={}}]}, {})
2017-11-22 15:01:29,955 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [3] setManagementRegistry(testServer1, [ClientStateSettings, ServerCacheCalls, ServerCacheSettings, ServerCacheStatistics])
2017-11-22 15:01:29,955 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231630050B61F02ACD8E2EA987AC000000001, data=[ContextualNotification{type='ENTITY_REGISTRY_AVAILABLE', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/pets:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/pets, entityType=org.terracotta.management.entity.sample.client.CacheEntity, consumerId=3}, attributes={}}]}, {})
2017-11-22 15:01:29,956 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [3] willPushEntityNotification(testServer1, ContextualNotification{type='SERVER_CACHE_CREATED', context={consumerId=3, alias=pet-clinic/pets, type=ServerCache, stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/pets:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/pets, entityType=org.terracotta.management.entity.sample.client.CacheEntity}, attributes={}})
2017-11-22 15:01:29,956 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231640050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='SERVER_CACHE_CREATED', context={consumerId=3, alias=pet-clinic/pets, type=ServerCache, stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/pets:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/pets, entityType=org.terracotta.management.entity.sample.client.CacheEntity}, attributes={}}]}, {})
2017-11-22 15:01:29,956 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform/entities, org.terracotta.management.entity.sample.client.CacheEntitypet-clinic/clients4)
2017-11-22 15:01:29,956 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverEntityCreated(testServer1, PlatformEntity{isActive=true, typeName='org.terracotta.management.entity.sample.client.CacheEntity', consumerID=4, name='pet-clinic/clients'})
2017-11-22 15:01:29,956 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231640050B61F02ACD8E2EA987AC000000001, data=[ContextualNotification{type='SERVER_ENTITY_CREATED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/clients:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/clients, entityType=org.terracotta.management.entity.sample.client.CacheEntity, consumerId=4}, attributes={}}]}, {})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [4] setManagementRegistry(testServer1, [ClientStateSettings, ServerCacheCalls, ServerCacheSettings, ServerCacheStatistics])
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231650050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='ENTITY_REGISTRY_AVAILABLE', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/clients:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/clients, entityType=org.terracotta.management.entity.sample.client.CacheEntity, consumerId=4}, attributes={}}]}, {})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [4] willPushEntityNotification(testServer1, ContextualNotification{type='SERVER_CACHE_CREATED', context={consumerId=4, alias=pet-clinic/clients, type=ServerCache, stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/clients:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/clients, entityType=org.terracotta.management.entity.sample.client.CacheEntity}, attributes={}})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231650050B61F02ACD8E2EA987AC000000001, data=[ContextualNotification{type='SERVER_CACHE_CREATED', context={consumerId=4, alias=pet-clinic/clients, type=ServerCache, stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=pet-clinic/clients:org.terracotta.management.entity.sample.client.CacheEntity, entityName=pet-clinic/clients, entityType=org.terracotta.management.entity.sample.client.CacheEntity}, attributes={}}]}, {})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform/entities, org.terracotta.management.entity.nms.agent.client.NmsAgentEntityNmsAgent1)
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverEntityCreated(testServer1, PlatformEntity{isActive=true, typeName='org.terracotta.management.entity.nms.agent.client.NmsAgentEntity', consumerID=1, name='NmsAgent'})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231650050B61F02ACD8E2EA987AC000000002, data=[ContextualNotification{type='SERVER_ENTITY_CREATED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=NmsAgent:org.terracotta.management.entity.nms.agent.client.NmsAgentEntity, entityName=NmsAgent, entityType=org.terracotta.management.entity.nms.agent.client.NmsAgentEntity, consumerId=1}, attributes={}}]}, {})
2017-11-22 15:01:29,957 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform/entities, org.terracotta.management.entity.nms.client.NmsEntityFailoverIT2)
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverEntityCreated(testServer1, PlatformEntity{isActive=true, typeName='org.terracotta.management.entity.nms.client.NmsEntity', consumerID=2, name='FailoverIT'})
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231660050B61F02ACD8E2EA987AC000000000, data=[ContextualNotification{type='SERVER_ENTITY_CREATED', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=FailoverIT:org.terracotta.management.entity.nms.client.NmsEntity, entityName=FailoverIT, entityType=org.terracotta.management.entity.nms.client.NmsEntity, consumerId=2}, attributes={}}]}, {})
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [2] setManagementRegistry(testServer1, [OffHeapResourceSettings, OffHeapResourceStatistics, StatisticCollectorCapability])
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.entity.nms.server.ActiveNmsServerEntity - [2] sendMessageToClients(DefaultMessage{type=NOTIFICATION, sequence=0000015FE55231660050B61F02ACD8E2EA987AC000000001, data=[ContextualNotification{type='ENTITY_REGISTRY_AVAILABLE', context={stripeId=SINGLE, serverId=testServer1, serverName=testServer1, entityId=FailoverIT:org.terracotta.management.entity.nms.client.NmsEntity, entityName=FailoverIT, entityType=org.terracotta.management.entity.nms.client.NmsEntity, consumerId=2}, attributes={}}]}, {})
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform, state)
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.TopologyService - [0] serverStateChanged(testServer1, ACTIVE)
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, platform, fetched)
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringDataListenerAdapter - [2] addNode(testServer1, , registry)
2017-11-22 15:01:29,958 [WorkerThread(l2_state_change_stage, 0)] TRACE org.terracotta.management.service.monitoring.DefaultDataListener - [2] setState(2, testServer1, [registry])
2017-11-22 15:01:29,962 [WorkerThread(l2_state_change_stage, 0)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(l2_state_change_stage, 0),5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
java.lang.AssertionError: [2] setState(2, testServer1, [registry]) IGNORED: sender is the current active server
	at org.terracotta.management.service.monitoring.Utils.warnOrAssert(Utils.java:50)
	at org.terracotta.management.service.monitoring.DefaultDataListener.setState(DefaultDataListener.java:97)
	at org.terracotta.management.service.monitoring.IStripeMonitoringDataListenerAdapter.addNode(IStripeMonitoringDataListenerAdapter.java:55)
	at com.tc.services.IStripeMonitoringWrapper.addNode(IStripeMonitoringWrapper.java:49)
	at com.tc.services.LocalMonitoringProducer$2.didEnterNode(LocalMonitoringProducer.java:145)
	at com.tc.services.LocalMonitoringProducer.walkCacheNode(LocalMonitoringProducer.java:348)
	at com.tc.services.LocalMonitoringProducer.walkCacheChildren(LocalMonitoringProducer.java:340)
	at com.tc.services.LocalMonitoringProducer.serverIsActive(LocalMonitoringProducer.java:142)
	at com.tc.objectserver.impl.DistributedObjectServer.lambda$createStageController$6(DistributedObjectServer.java:865)
	at com.tc.async.impl.StageController.transition(StageController.java:88)
	at com.tc.l2.handler.L2StateChangeHandler.handleEvent(L2StateChangeHandler.java:60)
	at com.tc.l2.handler.L2StateChangeHandler.handleEvent(L2StateChangeHandler.java:34)
	at com.tc.async.impl.AbstractStageQueueImpl$HandledContext.runWithHandler(AbstractStageQueueImpl.java:216)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:231)
```

**Comment by mathieucarbou** [comment]
UPDATE: See PR https://github.com/Terracotta-OSS/terracotta-platform/pull/413 and run `FailoverIT`.

**Comment by mathieucarbou** [comment]
UPDATE: I also tried to modify my `IStripeMonitoring.addNode()` implementations to return `false`, so that the caller (platform) does not cache it, since the api doc says: `@return True if the node was created/replaced.  False if a parent couldn't be found.`

But it doesn't work, the values that were sent from the old passive to the active gets replied, whether I return false or not to the `addNode()` calls.

**Comment by myronkscott** [comment]
I think the problem here is that you are getting information from two separate channels and trying to relate them when they are not directly relatable.  Both channels are instances of `org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter`, one fetched from the registry by the platform itself and the second fetched by an entity or entities.  What is  piped into the platform fetched service should not be intermingled with the entity fetched instance (unless the underlying service implementation supports it). 

Whenever a failover happens, the new active will faithfully replay everything it knows about what has been reported to each instance `org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter` on not only the new active but on all remaining passives.  This is so a full view of the environment can be recreated on failover.  Once the view has been recreated, all cached state for that active is flushed.  If we turn this off, any state reported in a passive not originating from the platform itself will be lost.

**Comment by mathieucarbou** [comment]
H @myronkscott , the `IStripeMonitoringPlatformListenerAdapter ` channel has no issue. Actually there is only 1 `IStripeMonitoringPlatformListenerAdapter `. How the `MonitoringServiceProvider` works is:

1. when platform asks for a `IStripeMonitoring` instance for consumer id 0 (platform), we return a singleton instance of `IStripeMonitoringPlatformListenerAdapter`. This implementation is used to receive platform events such as client connecting, disconnecting, server became active, etc.

2. when platform asks for a `IStripeMonitoring` instance for a consumer id _that is not 0_, it means that platform wants to deliver to us states or data __coming from the passive servers.__ In this case, we return a new `IStripeMonitoringDataListenerAdapter` instance, implementing only the `IStripeMonitoring` methods related to states and `pushBestEffortsData`.

After a failover, `IStripeMonitoringPlatformListenerAdapter` works fine.

What is not working is that we still receive callbacks from the previously created `IStripeMonitoringDataListenerAdapter` instances for the _passive entities_, whereas these entities __have already been promoted__ and the server __has already became active.__

**Comment by myronkscott** [comment]
This is the way this structure is intended to work.  If you do not want the nodes readded to the tree on failover you need to remove them. This is so the structure looks the same after failover minus those branches related to missing servers

**Comment by myronkscott** [comment]
This the problem may be the mis-interpretation of what is happening in #2.  The platform will only ever add nodes on consumerid 0 either from the local server (active) or remote servers (passive). Anything on other consumerids are from entities either local or remote.  These will always be replayed because the platform has no idea what an entity has put into the tree and assumes that the entity wants it there either active or passive. Can you just have the active version of the entity remove the nodes you don’t want when it fetches the service?

**Comment by mathieucarbou** [comment]
Hi @myronkscott,
We cannot because we do not know what has been added. Only the passives cache some data. Also, on passive server, we are using only:

1. addNode
2. pushBestEffortsData

I already told Jeff some time ago t we do not need this tree structure from passive to active and we do not need caching and replay. What we need is:

1. pushData (to send management call responses in a reliable way from passive to active)
2. pushBestEffortsData (to send notifications and stats from passive to active)

Ideally, we would like to also send notifications with the first channel.

Currently, pushData does not exist so we are forced to reuse this tree structure tha tcompletely does not fit what we need. So each tine a management call is made, we call:

`addNode(server, call-answer, uuid)`

So that the active receives the answer in a reliable way. __It means that on passive servers the tree keeps growing and growing in memory__ because we have no way to clean what the server caches, and this caches is completely useless.

The tree structure is only relevant on an active server so that platform inform us about the topology. But on passive servers, there is no topology, only events and message answers that are sent eitehr from a reliable way, either from an non reliable way.

**Comment by mathieucarbou** [comment]
UPDATE: I tried to move everything to the non-reliabe channel (pushBestEffortData) in commit https://github.com/mathieucarbou/terracotta-platform/commit/c39aab9758ed6675453c2142de9b52ff884a1860 but it does not work: sometimes we do not receive some important data. So I have some tests failures.

We need a way to have a reliable communication channel without caching, like pushBestEffortData, but that is reliable.

**Comment by mathieucarbou** [comment]
talked with @myronkscott : a solution will be implemented in PR https://github.com/Terracotta-OSS/terracotta-platform/pull/413/commits
