### ISSUE TITLE
Client reconnect fails with assertion error : Assert.eval(!isConnected())

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#936]
While testing coordination details I'm seeing sporadic failures (1 out of 500 failovers) to reconnect in the clients with the following assertion error:
```
0 WARN  [ConnectionEstablisher-[localhost:15146, localhost:15148]-1593112773] ClientMessageTransport:247 - ConnectionID(16.0b83888225e44b459482e37e25f1fe29.725b7248-a7a0-4e3d-bec3-3fa5c3677c09-1653beab155.Stripe): Reconnect failed !
com.tc.util.TCAssertionError: Assertion failed
	at com.tc.util.Assert.failure(Assert.java:55)
	at com.tc.util.Assert.eval(Assert.java:64)
	at com.tc.net.protocol.transport.ClientMessageTransport.reconnect(ClientMessageTransport.java:416)
	at com.tc.net.protocol.transport.ClientMessageTransport.reopen(ClientMessageTransport.java:410)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher.reconnect(ClientConnectionEstablisher.java:242)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher$AsyncReconnect.run(ClientConnectionEstablisher.java:515)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chrisdennis** [comment]
Failure in CI: http://jenkins.terracotta.eur.ad.sag:8080/job/pipelines/job/TAB/job/terracotta-enterprise/job/PR-1884/66/
