### ISSUE TITLE
Infinite looping on weakhashmap

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#967]
This seems happening from possible dead code  on TCByteBufferFactory.java probably due to corrupted state. I saw this on a hanged build as well last week.

https://github.com/Terracotta-OSS/terracotta-core/blob/master/tc-messaging/src/main/java/com/tc/bytes/TCByteBufferFactory.java

"pool-129-thread-2" #2094 prio=5 os_prio=0 tid=0x00007fb2c1b62000 nid=0x9099 runnable [0x00007fb2d7372000]
   java.lang.Thread.State: RUNNABLE
            at java.util.WeakHashMap.put(WeakHashMap.java:453)
            at java.util.Collections$SetFromMap.add(Collections.java:5461)
            at com.tc.bytes.TCByteBufferFactory.registerThreadGroup(TCByteBufferFactory.java:86)
            at com.tc.async.api.SEDA.<init>(SEDA.java:38)
            at com.tc.object.DistributedObjectClient.<init>(DistributedObjectClient.java:183)
            at com.tc.client.ClientFactory.createClient(ClientFactory.java:36)

**Comment by myronkscott** [comment]
fixed in 1e3a95925d
